 server:
   port: 9090
   uri: "http://stats-server:9090"
 spring:
   main.banner-mode: OFF
   jpa:
     properties:
       hibernate:
         format_sql: true
         jdbc.time_zone: UTC
         database: H2
         show-sql: true
         sql.init.mode: always
       datasource:
         url: jdbc:h2:file:./db/filmorate
         driverClassName: org.h2.Driver
         username: sa
         password: password
 logging.level.org.springframework:
    orm.jpa: INFO
