server:
  port: 8080
  url: http://localhost:8080
stats-server:
  url: http://stats-server:9090
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    database: POSTGRESQL
    show-sql: true
  sql:
    init:
      mode: always
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main-service
    username: vxuser
    password: vxpasswd
logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        transaction: INFO
